docs/clinic-flame.txt
in default mode, flame no longer needs sudo, and supports windows
=> remove sudo/windows non-support notice

package.json
It refuses to install against node 10.8.0 due to the spec in `package.json`. After adjusting node engines the tests are still passing.
=> Match package.json node engines to the docs

bin.js, test/cli-bubbleprof-visualize-only.test.js, test/cli-doctor-visualize-only.test.js, test/cli-flame-visualize-only.test.js
Fixes an issue where the visualizer HTML file could be output to `{pid}.clinic-{tool}/.html`.
This fixes it for all tools, because the output file name is passed in by the Clinic CLI and not determined separatly in each tool.
=> Strip trailing slash from --visualize-only.

bin.js
The flame CLI has some tests now so we don't need to opt out of coverage.
=> Remove coverage ignore comments for Flame.

package.json
Should fix #94
There is a reference to `autocannon` [here](https://github.com/nearform/node-clinic/blob/master/bin.js#L289), but I guess since it's in the `devDependencies` it's not getting installed.
=> Move autocannon out of dev dependencies

bin.js
In --collect-only, the CLI wasn't stopping the spinner after it completed. The spinner uses `setInterval` so it would just keep going indefinitely, preventing the process from exiting. Now it's correctly stopped.
=> Fix infinite spinner on --collect-only

bin.js, docs/clinic-login.txt, docs/clinic-logout.txt, docs/clinic-upload.txt, docs/clinic-user.txt, lib/authenticate.js, lib/tar-and-upload.js, package.json, test/cli-ask-full.test.js, test/cli-login-logout.test.js, test/cli-upload-files.test.js
Stores the JWT in ~/.node-clinic-rc after logging in. ~/.node-clinic-rc is a JSON file with upload URLs as keys, JWTs as values.
Use `clinic login` to login manually. Optionally specify an `--upload-url`.
Use `clinic logout` to logout manually. Optionally specify an `--upload-url`. Add `--all` to log out of all Clinic Upload servers, this deletes the ~/.node-clinic-rc file.
Use `clinic user` to show a list of current sessions. Optionally specify an `--upload-url` to only show that session.
You can use the `CLINIC_CREDENTIALS` environment variable to point to a different file. I added this for tests, maybe it's also useful in programmatic environments and warrants docs?
`clinic upload` and `clinic ask` automatically do what `clinic login` does at the start.
TODO:
=> Store auth tokens in ~/.node-clinic-rc

.gitignore, bin.js, docs/clinic-bubbleprof.txt, docs/clinic-doctor.txt, docs/clinic-flame.txt, lib/clean.js, test/cli-bubbleprof-collect-only.test.js, test/cli-bubbleprof-full.test.js, test/cli-bubbleprof-visualize-only.test.js, test/cli-clean-full.test.js, test/cli-doctor-collect-only.test.js, test/cli-doctor-full.test.js, test/cli-doctor-visualize-only.test.js, test/cli-flame-full.test.js, test/cli-flame-visualize-only.test.js
Avoids polluting the user's working directory with a ton of different files.
`clinic clean` now removes `.clinic` as well as old-style `{pid}.clinic-{tool}` files.
=> Set default output directory to $cwd/.clinic

package.json
This was used for a while during the configuration of Azure Pipelines,
but was removed in https://github.com/nearform/node-clinic/pull/93/commits/2179cd81b1f0fd329d38bf04be9ed16bc8df2689
before that PR was merged.
Closes #123
=> Remove unused tap-junit

test/cli.js
We have quite a few tests that assert that something went wrong in the
expected way, and each of these would log debugging output. That's fine
on its own but it did make test output eg on CITGM quite confusing,
because many of the things that look like failures are actually not.
These can be added back easily locally of course for debugging :)
=> Reduce test output noise

test/cli-doctor-full.test.js
this one has been a bit flakey as of late. they fail because we expect 2+ samples to be taken. normally, 1 should be taken every 10ms. the test programs in our doctor unit tests run for 100ms. sometimes, that's not enough to take 2 samples.
here, i've bumped the runs to take 400ms. in tests in the doctor repo, we allow 100ms of flakiness for the sample interval, so i took that and added a few 100ms more to make sure that we actually have >2 samples.
Closes https://github.com/nearform/node-clinic/issues/131
Closes https://github.com/nearform/node-clinic/issues/139
Closes https://github.com/nearform/node-clinic/issues/140
this should also address the cause of some recent CITGM failure, eg https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1768/nodes=win-vs2017/testReport/(root)/citgm/ …
=> test: allow more time for doctor to take samples

lib/tar-and-upload.js, test/tar-and-upload.test.js
The upload server will have some useful error messages for duplicate uploads or uploads that don't contain any files. This bubbles that information up to the user.
=> Display error message from server if available

package.json, test/cli.js
Helps with disk space on long running machines (eg CITGM ran into space
issues)
And with RAM usage on low end laptops with an in-memory /tmp :)
=> Cleanup temporary profiles after test run

package.json, test/cli-autocannon.test.js
env-string@1.0.1 supports backslash-escapes, this adds some tests.
=> Test backslash-escaping $NOT_ENV_VARS in --autocannon URL

lib/authenticate.js, test/authenticate.test.js
When in an SSH session, or when a browser cannot be opened using the `open` module, print the authentication link so you can visit it manually.
Initially I only had the `open()` fallback, but I found that some of the servers I tested with had text-based browsers like elinks or w3m installed. When those were launched, `xdg-open` would exit with 0, but the browser would run in the background, impossible to interact with. Hence the explicit SSH check. This probably accounts for the vast majority of likely configurations.
Closes #147
=> Print authentication URL if browser is not available

bin.js
Looking to solve issue #194. At the moment this will:
- Check the params passed for npm start.
- Exit the process. 
- Show help for doctor.
Could potentially change the params check to be !node instead and throw error instead of showing help for doctor. As it stands this behaviour is better since it doesn't follow the process right to the very end like it did before.
=> Check if npm start passed

README.md, azure-pipelines-npm-template.yml, package.json
Node.js 8 is no longer officially supported, and we're using an API from Node.js 10.12 now.
=> Drop support for Node.js < 10.12.0

.gitignore, README.md, bin.js, docs/clinic-doctor.txt, docs/clinic-flame.txt, package.json
Related to this PR:
Doctor
https://github.com/nearform/node-clinic-doctor/pull/295
Flame
https://github.com/nearform/node-clinic-flame/pull/107
0x
https://github.com/davidmarkclements/0x/pull/222
~BubbleProf - Will be separate from this change
https://github.com/nearform/node-clinic-bubbleprof/pull/346~
The "--collect-delay" arg will be passed in with the arguments and allow the collection of data to be delayed.
=> Pass collectDelay arg to Clinic Doctor/Flame

.gitignore, bin.js, test/cli-bubbleprof-non-node.test.js, test/cli-doctor-non-node.test.js, test/cli-flame-non-node.test.js
Noticed something was missing from the `clinic tool -- node x.js` check
that we added recently. Its purpose is to prevent you from doing things
like `clinic tool -- sh wrapper.sh`, which is unsupported. But the check
was a bit too tight: it prevented that exact input, but not inputs with
additional flags like `clinic tool --no-open -- sh wrapper.sh`. This
change fixes that, adds support for providing full paths to the node.js
binary like `clinic tool -- /usr/bin/node script.js`, and adds tests.
=> Tweak `node` argument check

package.json
As far as I can see this is the only thing in order to fix https://github.com/nearform/node-clinic/issues/254.
Node 14 is already in the ci workflow and all tests are green. I also tested it locally on some simple apps and it appears to be working properly.
Linked to this I also added node 14 to the ci workflow of doctor, bubbleprof and flame to make sure they independently work with Node 14:
https://github.com/nearform/node-clinic-doctor/pull/334
https://github.com/nearform/node-clinic-flame/pull/130
https://github.com/nearform/node-clinic-flame/pull/130
=> Add node 14 to supported engines

README.md, bin.js, docs/clinic-flame.txt, docs/clinic-heap-profiler.txt, docs/clinic.txt, package.json, test/cli-bubbleprof-non-node.test.js, test/cli-bubbleprof-visualize-only.test.js, test/cli-doctor-non-node.test.js, test/cli-doctor-visualize-only.test.js, test/cli-flame-non-node.test.js, test/cli-flame-visualize-only.test.js, test/cli-heapprofiler-full.test.js, test/cli-heapprofiler-help.test.js, test/cli-heapprofiler-no-args.test.js, test/cli-heapprofiler-non-node.test.js, test/cli-heapprofiler-version.test.js, test/cli-heapprofiler-visualize-only.test.js
This PR add support for the Heap Profiler and memory flame charts via https://github.com/clinicjs/node-clinic-heap-profiler.
This PR cannot be merged until https://github.com/clinicjs/node-clinic-heap-profiler/pull/1 lands and the package is finally released on NPM.
=> Add heap profiler to the CLI

.github/workflows/ci.yml, README.md, bin.js, docs/clinic-bubbleprof.txt, docs/clinic-doctor.txt, docs/clinic-flame.txt, docs/clinic-heap-profiler.txt, package.json, test/cli-bubbleprof-stop-delay.test.js, test/cli-doctor-stop-delay.test.js, test/cli-flame-stop-delay.test.js, test/cli-heapprofiler-stop-delay.test.js
Address: https://github.com/clinicjs/node-clinic-doctor/issues/362
=> feat: add stop delay arg

.gitignore
The `ctags`(used for jump into definitions﻿) create a `tags` file for cache
=> chore: add tags to gitignore

.github/workflows/ci.yml, test/cli-heapprofiler-full.test.js
This test was intermitent, because `autocannon` is no﻿t available globally (sometimes).
=> fix: intermitent test

package.json
Fixes runtime issue on latest macOS
❯  clinic flame -- node dist/index.js
/Users/tjmehta/Developer/@codeshare/api/node_modules/macos-release/index.js:26
const [name, version] = nameMap.get(release);
^
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
=> bump insight@0.11.1

README.md
Changes:
- fix: provide a workaround to start profiling within `CMD` command in the [podman](https://podman.io/) container environment (docker alternative)
=> Fix / Extend Readme With A Workaround For Podman Container

.github/workflows/ci.yml
This is useful to run the CI when the data source isn't actively maintained.
=> workflow: add workflow_dispatch to CI

README.md, bin.js, docs/clinic-bubbleprof.txt, docs/clinic-doctor.txt, docs/clinic-flame.txt, docs/clinic-heap-profiler.txt
This introduces a new CLI flag, `--name`. It allows the user to specify an identifier for their report. For instance, let's imagine you are profiling a Node.js 18 app and performing the improvements on the flight. 
```console
$ clinic flame --name v18-test --autocannon [ / ] -- node index.js
```
It will generate the following tree:
```console
.clinic
├── v18-test.clinic-flame
│   ├── v18-test.clinic-flame-inlinedfunctions
│   ├── v18-test.clinic-flame-samples
│   └── v18-test.clinic-flame-systeminfo
└── v18-test.clinic-flame.html
```
And every time I run the clinic flame script, it will update the current file (`v18-test.clinic-flame*`), so I just need to reload my .html page.
=> feat: accept --name argument
